PROBLEM_SUBJECTS = {
    'basic_math': {
        'short name': 'Basic Math',
        'description': 'Basic Mathematics',
        'categories': {
            "Whole Numbers": [
                "Place values (Whole Numbers).",
                "Rounding.",
                "Estimating sums.",
                "Simple addition (1 digit).",
                "Simple addition (1 - 2 digits).",
                "Addition (3 digits).",
                "Associative property (addition).",
                "Commutative property (addition).",
                "Addition word problem.",
                "Estimating differences.",
                "Simple subtraction (1 digit).",
                "Simple subtraction without borrowing (1 or 2 digits).",
                "Simple subtraction (1 or 2 digits).",
                "Subtraction.",
                "Subtraction (from 10x).",
                "Subtraction word problem.",
                "Simple multiplication (1 or 2 digits).",
                "Simple multiplication II.",
                "Simple multiplication (by 10x).",
                "Estimating products.",
                "Multiplication (2 or 3 digits).",
                "Write number in expanded form.",
                "Simplifying expanded form.",
                "Multiplication word problem.",
                "Simple division (no remainder).",
                "Simple division with zeros (no remainder).",
                "Estimating quotients.",
                "Simple division (with remainder).",
                "Division word problem.",
                "Long division (no remainder).",
                "Long division (with remainder).",
                "Square roots.",
                "Order of operations.",
                "Order of operations (exponents).",
                "Order of operations II.",
                "Telling time I.",
                "Telling time II.",
                "Passing Time.",
                "Passing Time Word Problem.",
                "Identify the operation word problem.",
                "Convert a Roman Numeral to a Standard Number.",
                "Convert to a Roman Numeral.",
                "Convert between place values.",
            ]
            "Decimals": [
                "Place values.",
                "Comparing decimals.",
                "Sorting decimals.",
                "Rounding decimals.",
                "Adding simple decimals.",
                "Adding decimals.",
                "Adding 3 decimals.",
                "Adding decimal word problem.",
                "Subtracting simple decimals.",
                "Subtracting decimals.",
                "Subtracting decimal word problem.",
                "Multiplying simple decimals.",
                "Multiplying 3 simple decimals.",
                "Multiplying decimals.",
                "Multiplying decimals (10x).",
                "Multiplying decimal word problem.",
                "Dividing simple decimals.",
                "Dividing decimals by whole numbers.",
                "Dividing decimals (10x).",
                "Dividing decimals by decimals.",
                "Dividing decimals by decimals II.",
                "Dividing decimal word problem.",
                "Write a number in scientific notation.",
                "Convert from scientific notation to standard notation.",
            ]
            "Fractions I": [
                "Identifying fractions.",
                "Identifying proper, improper, and mixed numbers.",
                "Plot a fraction on a number line.",
                "Find the greatest common factor of two numbers (GCF).",
                "Writing numbers as products of primes using exponents.",
                "Reducing fractions.",
                "Higher equivalent fractions.",
                "Comparing fractions.",
                "Sorting fractions.",
                "Improper fractions to mixed numbers.",
                "Mixed numbers to improper fractions.",
                "Multiplying simple fractions.",
                "Multiplying fractions word problem.",
                "Multiplying fractions with canceling.",
                "Multiplying 3 fractions.",
                "Multiplying a whole number and a fraction.",
                "Multiplying mixed numbers and a fraction.",
                "Multiplying mixed numbers and a whole number.",
                "Multiplying mixed numbers.",
                "Dividing simple fractions.",
                "Dividing with mixed numbers.",
                "Find a fraction of a number.",
                "Find what fraction.",
                "Find a number given a fraction of it.",
            ]
            "Fractions II": [
                "Finding the lowest common multiple.",
                "Finding the lowest common multiple word problem.",
                "Adding fractions with common denominators.",
                "Adding 3 fractions with common denominators.",
                "Adding mixed numbers with common denominators.",
                "Adding 3 mixed numbers with common denominators.",
                "Adding fractions using the commutative and associative properties.",
                "Adding fractions with uncommon denominators.",
                "Adding fractions with uncommon denominators (1 digit).",
                "Adding 3 fractions with uncommon denominators.",
                "Adding mixed numbers with uncommon denominators.",
                "Adding 3 mixed numbers with uncommon denominators.",
                "Adding mixed numbers word problem.",
                "Subtracting fractions with common denominators.",
                "Subtracting mixed numbers with common denominators.",
                "Subtracting fractions with uncommon denominators.",
                "Subtracting mixed numbers with uncommon denominators.",
                "Subtracting fractions from a whole number.",
                "Subtracting fractions with borrowing.",
                "Subtracting mixed numbers word problem.",
                "Converting fractions to decimals (no mixed numbers).",
                "Converting decimals to fractions (no mixed numbers).",
                "Converting fractions to decimals.",
                "Converting decimals to fractions.",
                "Repeating decimals to fractions.",
                "Sorting decimals and fractions.",
            ]
            "Ratios, Proportions, and Percents": [
                "Simplifying ratios.",
                "Ratio word problem.",
                "Ratio word problem II.",
                "Solving proportions (simple values).",
                "Solving proportions.",
                "Simple proportion word problem.",
                "Proportion word problem (height and shadow).",
                "Proportion word problem (fractions).",
                "Converting decimals to percents.",
                "Converting percents to decimals.",
                "Converting fractions to percents.",
                "Converting percents to fractions.",
                "Convert inches to centimeters.",
                "Convert centimeters to inches.",
                "Convert miles to kilometers.",
                "Convert kilometers to miles.",
                "Convert simple metric lengths.",
                "Convert simple English lengths.",
                "Convert simple metric masses.",
                "Convert simple English weights.",
                "Convert simple metric volumes.",
                "Convert simple English volumes.",
                "Convert using the metric system.",
                "Convert using the English system.",
                "Convert using the metric and English system.",
                "Convert between simple units of time.",
                "Converting simple metric lengths word problem.",
                "Converting simple English lengths word problem.",
                "Converting simple metric masses word problem.",
                "Converting simple English weights word problem.",
                "Converting between derived quantities word problem.",
                "Find the percent of a number.",
                "Find what percent.",
                "Find a number given its percent.",
                "Simple Percent word problem (percent of).",
                "Simple Percent word problem (find the whole).",
                "Simple Percent word problem (find the percent).",
                "Simple Percent word problem (sale).",
                "Percent word problem (sale).",
                "Simple Percent word problem (find the tax).",
                "Simple Percent word problem (tax).",
                "Percent word problem (tax).",
                "Percent word problem (find the tax percentage).",
                "Percent word problem (sale and tax).",
                "Find a fraction of a number.",
                "Find what fraction.",
                "Find a number given a fraction of it.",
            ]
            "Statistics and Probablity": [
                "Bar graphs.",
                "Bar graphs (smaller).",
                "Make a bar graph given when data.",
                "Line graphs.",
                "Line graphs (smaller).",
                "Pie charts.",
                "Analyzing graphs.",
                "Mean (whole answers).",
                "Mean.",
                "Mean word problem.",
                "Median.",
                "Median word problem.",
                "Mode.",
                "Mode (no mode added).",
                "Mode word problem.",
                "Range.",
                "Range word problems.",
                "Standard deviation.",
                "Simple reverse mean word problem (whole numbers).",
                "Reverse mean word problem (whole numbers).",
                "Reverse mean word problem.",
                "Overall average word problem.",
                "Basic probability word problem (marbles).",
                "Basic probability word problem (students).",
                "Probability word problem (with replacement).",
                "Probability word problem (no replacement).",
                "Experimental probability word problem.",
            ]
            "Basic Algebra": [
                "Adding integers (1-digit).",
                "Adding 3 - 4 integers (1-digit).",
                "Adding integers.",
                "Adding 3 - 4 integers.",
                "Adding integers word problem.",
                "Subtracting integers (1-digit).",
                "Subtracting integers.",
                "Multiplying integers (1-digit).",
                "Multiplying 3 - 4 integers (1-digit).",
                "Multiplying integers.",
                "Dividing integers (1-2 digits).",
                "Dividing integers.",
                "Integer word problem.",
                "Basic exponents (powers).",
                "Evaluate a basic root.",
                "Evaluating expressions (Basic one operation).",
                "Evaluating expressions (Basic two operations).",
                "Evaluating expressions I.",
                "Evaluating expressions II.",
                "Applying area formulas.",
                "Functions - Table.",
                "Functions.",
                "Solving single-step equations by subtraction (1-digit no negatives).",
                "Solving single-step equations by subtraction (1-digit).",
                "Solving single-step equations by subtraction.",
                "Solving single-step equations by addition (1-digit no negatives).",
                "Solving single-step equations by addition (1-digit).",
                "Solving single-step equations by addition.",
                "Solving single-step equations by addition or subtraction (1-digit).",
                "Solving single-step equations by addition or subtraction.",
                "Solving single-step equations by division (simple values no negatives).",
                "Solving single-step equations by division.",
                "Solving single-step equations by multiplication (1-digit no negatives).",
                "Solving single-step equations by multiplication.",
                "Solving two-step equations (simple values).",
                "Solving two-step equations.",
                "Plot a point on a coordinate plane.",
                "Find the slope given 2 points.",
                "Given a graph, calculate the slope.",
                "Graph by using an x-y table (y is isolated).",
                "Given a point and an equation in slope-intercept form, determine if the point exists on the line.",
                "Graph a line given an equation in slope-intercept form.",
            ]
            "Basic Geometry": [
                "Identifying shapes.",
                "Perimeter.",
                "Circumference (pi).",
                "Circumference (3.14).",
                "Area of a circle (pi).",
                "Area of a circle (3.14).",
                "Area of a square (blocks).",
                "Area of a rectangle (blocks).",
                "Volume of a cube (blocks).",
                "Volume of a rectangular solid (blocks).",
                "Area of a square or rectangle.",
                "Area of a parallelogram.",
                "Area of a triangle.",
                "Area of a trapezoid.",
                "Area word problem.",
                "Volume of a cube.",
                "Volume of a rectangular prism.",
                "Volume of a cylinder (pi).",
                "Volume of a cylinder (3.14).",
                "Volume of a sphere (pi).",
                "Volume of a sphere (3.14).",
                "Similar polygons.",
                "Pythagorean theorem.",
                "Pythagorean theorem word problem.",
            ]
        }
        'enabled': False
    },
    'algebra_1': {
        'short name': 'Algebra I',
        'description': 'Algebra I',
        'categories': {
            "Arithmetic": [
                "Addition.",
                "Addition word problems.",
                "Subtraction.",
                "Subtraction word problem.",
                "Multiplication.",
                "Multiplication word problem.",
                "Division.",
                "Division word problem.",
                "Order of operations.",
                "Order of operations II.",
                "Order of operations with absolute values.",
            ],
            "Real Numbers": [
                "Plot a point on a number line.",
                "Absolute values.",
                "Adding integers (1-digit).",
                "Adding 3 - 4 integers (1-digit).",
                "Adding integers.",
                "Adding integers word problem.",
                "Adding 3 - 4 integers.",
                "Subtracting integers (1-digit).",
                "Subtracting integers.",
                "Subtracting integers word problem.",
                "Adding and subtracting integers.",
                "Multiplying integers (1-digit).",
                "Multiplying 3 - 4 integers (1-digit).",
                "Multiplying integers.",
                "Dividing integers (1-2 digits).",
                "Dividing integers.",
                "Integer word problem.",
                "Graphing inequalities on a number line.",
                "Graphing 2 inequalities on a number line (conjunctions and disjunctions).",
            ],
            "Decimals, Fractions, and Percents": [
                "Adding and subtracting decimals.",
                "Multiplying decimals.",
                "Dividing decimals.",
                "Adding and subtracting fractions.",
                "Adding fractions using the commutative and associative properties.",
                "Multiplying fractions.",
                "Multiplying fractions word problem.",
                "Dividing fractions.",
                "Converting fractions to decimals.",
                "Converting decimals to fractions.",
                "Converting decimals to percents.",
                "Converting percents to decimals.",
                "Converting fractions to percents.",
                "Converting percents to fractions.",
                "Simple percent word problem.",
                "Percent word problem (sale).",
                "Percent word problem (tax).",
                "Percent remaining word problem.",
            ],
            "Introduction to Variables": [
                "Solving for variables using mental math.",
                "Adding and subtracting variables.",
                "Simple literal expression.",
                "Simple literal expression word problem (add and sub).",
                "Simple literal expression word problem (multi and div).",
                "Literal expressions I.",
                "Literal expressions II.",
                "Multiplying variables.",
                "Dividing variables.",
                "Combining like terms I.",
                "Combining like terms II.",
                "Using the distributive property (no exponents).",
                "Using the distributive property.",
                "Using the distributive property (2 variables).",
                "Distribute and Evaluate.",
                "Evaluating expressions (Basic one operation).",
                "Evaluating expressions (Basic two operations).",
                "Evaluating expressions I.",
                "Evaluating expressions II.",
                "Combining like terms and evaluating expressions.",
                "Solve and then evaluate an expression.",
                "Applying area formulas.",
                "Functions - Table.",
                "Functions.",
                "Add and Subract simple fractions with variables.",
                "Add and Subract simple fractions with variables (exponents).",
                "Add and Subract rational expressions with uncommon denominators.",
            ],
            "Solving single-step equations and inequalities": [
                "Solving single-step equations by subtraction (1-digit no negatives).",
                "Solving single-step equations by subtraction (fractions, no negatives).",
                "Solving single-step equations by subtraction (1-digit).",
                "Solving single-step equations by subtraction (fractions).",
                "Solving single-step equations by subtraction.",
                "Solving single-step equations by addition (1-digit no negatives).",
                "Solving single-step equations by addition (fractions, no negatives).",
                "Solving single-step equations by addition (1-digit).",
                "Solving single-step equations by addition (fractions).",
                "Solving single-step equations by addition.",
                "Solving single-step equations by addition or subtraction (one digit and positive answers).",
                "Solving single-step equations by addition or subtraction.",
                "Solving single-step equations by addition or subtraction (variable on the right).",
                "Solving single-step equations by addition or subtraction II.",
                "Solving single-step equations by addition or subtraction word problem.",
                "Solving single-step equations by division (simple values no negatives).",
                "Solving single-step equations by division.",
                "Solving single-step equations by division (variable on the right).",
                "Solving single-step equations by multiplication (1-digit no negatives).",
                "Solving single-step equations by multiplication.",
                "Solving single-step equations by multiplication (variable on the right).",
                "Solving single-step equations by taking the reciprocal (no negatives).",
                "Solving single-step equations by taking the reciprocal.",
                "Solving single-step inequalities by addition or subtraction.",
                "Solving single-step inequalities by division.",
                "Solving single-step inequalities by multiplication.",
                "Solving single-step inequalities by taking the reciprocal.",
            ],
            "Solving multi-step equations": [
                "Solving two-step equations (simple values no negatives).",
                "Solving two-step equations (simple values).",
                "Solving two-step equations.",
                "Solving two-step equations (variable on the right).",
                "Solving multi-step equation word problem.",
                "Solving equations with the distributive property (first step).",
                "Solving equations with the distributive property.",
                "Solving equations by combining like terms I.",
                "Solving equations by combining like terms II.",
                "Solving equations with the distributive property and by combining like terms.",
                "Solving equations with absolute values I.",
                "Solving equations with absolute values II.",
                "Solving equations with inequalities.",
                "Solving equations with inequalities and absolute values.",
                "Solving with variables on both sides (1-digit).",
                "Solving with variables on both sides.",
                "Solving an equation word problem.",
                "Solving for a variable in terms of other variables.",
                "Solving for a variable in terms of other variables (more advanced).",
                "Direct and indirect variation word problems.",
                "Direct and indirect variation squared word problems.",
                "Rate word problems I.",
                "Rate word problems II.",
                "Rate word problems III.",
                "Work word problems.",
                "Work word problems (find an individual time).",
                "Solving rational expressions I.",
                "Solving rational expressions II.",
            ],
            "Graphs": [
                "Read a bar graph.",
                "Read a bar graph (smaller).",
                "Read a line graph.",
                "Read a line graph (smaller).",
                "Extend a line graph to solve a problem.",
                "Plot a point on a coordinate plane.",
                "Find the ordered pair.",
                "Find the distance between 2 points.",
                "Given a graph, use the vertical line test to check if the graph is a function.",
                "Create a Box-and-Whisker Plot.",
                "Read a Box-and-Whisker Plot.",
                "Approximate a trend line for a Scatter Plot.",
            ],
            "Introduction to Graphing": [
                "Graph by using an x-y table with given x-values.",
                "Graph by using an x-y table with given x-values (includes fractional slope).",
                "Graph by using an x-y table (y is isolated).",
                "Graph by using an x-y table.",
                "Slope word problem (ramp).",
                "Find the slope given 2 points.",
                "Rate of change word problem.",
                "Given a graph, calculate the slope.",
                "Given a point and an equation in slope-intercept form, determine if the point exists on the line.",
                "Given a point and an equation in point-slope form, determine if the point exists on the line.",
                "Given a point and an equation in standard form, determine if the point exists on the line.",
                "Calculate the y-intercept of an equation given in slope-intercept form.",
                "Calculate the x-intercept of an equation given in slope-intercept form.",
                "Calculate the x and y-intercept of an equation given in slope-intercept form.",
                "Calculate the y-intercept of an equation given in point-slope form.",
            ],
            "Graphing Linear Equations": [
                "Identify the slope and y-intercept given an equation in slope-intercept form.",
                "Write an equation in slope-intercept form when given the slope and y-intercept.",
                "Graph a line given an equation in slope-intercept form (no fractions).",
                "Graph a line given an equation in slope-intercept form.",
                "Graph a line given an equation in slope-intercept form (includes undefined lines).",
                "Write an equation in slope-intercept form when given a graph.",
                "Given an x-y table, write an equation in slope-intercept form.",
                "Write an equation in slope-intercept form that passes through a given point and slope.",
                "Find a slope that is parallel or perpendicular to a line.",
                "Write an equation in slope-intercept form that passes through a point and is parallel to a line.",
                "Write an equation in slope-intercept form that passes through a point and is perpendicular to a line.",
                "Graph a line given a point and the slope.",
                "Graph a line given an equation in point-slope form.",
                "Write an equation in point-slope form.",
                "Graph a line given an equation in standard form.",
                "Write an equation in standard form.",
                "Standard form to slope-intercept form.",
            ],
            "Graphing Inequalities": [
                "Graph an inequality in slope-intercept form.",
                "Given an inequality, find its corresponding equation.",
                "Graph 2 inequalities in slope-intercept form.",
                "Graph 3 inequalities in slope-intercept form.",
                "Graph an inequality in standard form.",
                "Graph 2 inequalities in standard form.",
                "Inequalities word problem.",
                "Graph 3 inequalities in standard form.",
                "Graph an inequality with a radical.",
            ],
            "Systems of Equations": [
                "Solve a system by graphing.",
                "Solve a system by substitution I.",
                "Solve a system by substitution II.",
                "Solve a system by elimination I (combination).",
                "Solve a system by elimination II (combination).",
                "Solve a system by elimination III (combination).",
                "Solve a system by any method.",
                "Solve a system by any method (mixing x and y location).",
                "Systems of equations word problem I.",
                "Systems of equations word problem II.",
                "Systems of equations word problem III.",
                "Systems of equations word problem IV.",
            ],
            "Roots and Exponents": [
                "Basic exponents.",
                "Basic exponents (positive and negative base).",
                "Multiplying basic exponents.",
                "Dividing basic exponents (positive exponent answers).",
                "Dividing basic exponents.",
                "Dividing basic exponents with negative exponents (positive exponents answers).",
                "Dividing basic exponents with negative exponents (negative exponents answers).",
                "Exponents (including negatives).",
                "Multiplying exponents (variables).",
                "Dividing exponents (variables).",
                "Multiplying and dividing exponents with variables.",
                "Exponents word problem.",
                "Write a number in scientific notation (positive).",
                "Write a number in scientific notation (negative).",
                "Write a number in scientific notation.",
                "Operations with scientific notation (addition/subtraction, positive exponents).",
                "Operations with scientific notation (addition/subtraction).",
                "Operations with scientific notation (multiplication).",
                "Operations with scientific notation (division).",
                "Write a number in standard form.",
                "Evaluate a basic root.",
                "Evaluate a root inside a root.",
                "Evaluate a root.",
                "Evaluate a root II.",
                "Estimate a root.",
                "Multiplying roots.",
                "Squaring a binomial with roots.",
                "Evaluate exponents that contain variables.",
                "Evaluate a term with a root and a variable.",
                "Solve an equation with a radical.",
                "Solve an equation with a radical II.",
                "Solve an equation with a radical III.",
                "Solve using the Pythagorean Theorem.",
                "Find the distance between two points using the distance formula.",
                "Graphing radicals.",
            ],
            "Polynomials": [
                "Polynomials in standard form.",
                "Adding and subtracting polynomials.",
                "Adding and subtracting functions.",
                "Adding and subtracting polynomials with common denominators.",
                "Simplifying polynomials.",
                "Distributing with polynomials.",
                "Distributing with polynomials word problem.",
                "Multiplying binomials.",
                "Multiplying polynomials.",
                "Multiplying functions without a leading coefficient.",
                "Multiplying functions.",
                "Dividing polynomials by one term.",
                "Dividing polynomials II.",
                "Dividing polynomials III.",
                "Dividing functions.",
                "Graphing a quadratic by using an x-y table.",
                "Graphing a quadratic by finding the vertex and the x-intercepts.",
                "Graphing a quadratic inequality.",
            ],
            "Factoring": [
                "Simple factoring.",
                "Simple factoring word problem.",
                "Factoring word problem.",
                "Factoring polynomials without a leading coefficient.",
                "Factoring binomial squares.",
                "Factoring difference of squares.",
                "Factoring polynomials with a leading coefficient.",
                "Simplifying polynomials by factoring I.",
                "Simplifying polynomials by factoring II.",
                "Solving factored polynomials.",
                "Solving polynomials by factoring I.",
                "Solving polynomials by factoring II.",
                "Solving polynomials by factoring III.",
                "Solving polynomials.",
                "Find the number of solutions using the discriminant.",
                "Solving polynomials using the quadratic equation.",
                "Completing the square.",
                "Solving polynomials by completing the square.",
            ]
        },
        'enabled': False
    },
    'geometry': {
        'short name': 'Geometry',
        'description': 'Geometry',
        'categories': {
            "Points, Lines, and Angles": [
                "Find the length of a segment using the midpoint.",
                "Find the length of a segment using the midpoint II.",
                "Find the measure of an angle.",
                "Find the measure of an angle II.",
                "Classify an angle.",
                "Complementary angles.",
                "Complementary angles II.",
                "Supplementary angles.",
                "Supplementary angles II.",
                "Vertical and Supplementary angles (simple).",
                "Vertical angles.",
                "Vertical angles II.",
                "Complementary angles word problem.",
                "Supplementary angles word problem.",
            ]
            "Constructions": [
                "Construct a line segment congruent to the given line segment.",
                "Construct a bisector of the given line segment.",
                "Construct an angle congruent to the given angle.",
                "Construct an angle bisector.",
                "Construct a perpendicular at the point given.",
                "Construct a perpendicular from a point not on a line.",
                "Construct a line parallel to a given line from a point.",
                "Construct an equilateral triangle.",
            ]
            "Triangles": [
                "Classify a triangle based on its angles.",
                "Classify a triangle based on its sides.",
                "Find the missing angle in a triangle.",
                "Find the missing angle in a triangle (Diagram).",
                "Find the missing angle in a triangle II.",
                "Find the missing angle in a isosceles triangle (Diagram).",
                "Solve for x using the triangle angle sum theorem.",
                "Find the missing angle outside of a triangle.",
                "Find the missing vertical angle.",
                "Calculate if two triangles on a coordinate plane are congruent.",
                "Congruent triangles.",
                "Missing angle word problem (right triangle).",
                "Find the length of a triangle midsegment.",
                "Find the length of a triangle base when given the midsegment.",
                "Find the length involving a median and centroid.",
            ]
            "Polygons": [
                "Convex and concave polygons.",
                "Special quadrilaterals.",
                "Classify the quadrilateral.",
                "Interior angle sum.",
                "Find the measure of each internal angle of a regular polygon.",
                "Exterior angle sum.",
                "Find the measure of each external angle of a regular polygon.",
                "Parallelogram angles.",
                "Parallelogram angles II.",
                "Parallelogram diagonals.",
                "Rectangle diagonals.",
                "Rhombus diagonals.",
                "Trapezoid medians.",
                "Trapezoid medians with variables.",
                "Interior angle sum word problem.",
            ]
            "Parallel Lines": [
                "Corresponding angles.",
                "Corresponding angles (Solving for x).",
                "Corresponding angles (Solving for x) II.",
                "Alternate interior angles.",
                "Alternate interior angles (Solving for x).",
                "Alternate interior angles (Solving for x) II.",
                "Alternate interior angles II.",
                "Alternate exterior angles.",
                "Alternate exterior angles (Solving for x).",
                "Alternate exterior angles (Solving for x) II.",
                "Parallel lines.",
                "Parallel lines word problem.",
            ]
            "Basic Proofs": [
                "If-Then statements.",
                "Converses of statements.",
                "Basic angle proof.",
                "Basic angle proof (some missing statements and reasons).",
                "Basic angle proof (all reasons are missing).",
                "Basic angle proof II.",
                "Basic angle proof II (some missing statements and reasons).",
                "Basic angle proof II (all reasons missing).",
                "Angle proof.",
                "Angle proof (some missing statements and reasons).",
                "Angle proof (all reasons are missing).",
                "Parallel line proof.",
                "Parallel line proof (some missing statements and reasons). ",
                "Parallel line proof (all reasons are missing). ",
            ]
            "Triangle Proofs": [
                "SSS congruent triangle proof.",
                "SSS congruent triangle proof (some missing statements and reasons).",
                "SSS congruent triangle proof (all reasons are missing).",
                "SAS congruent triangle proof.",
                "SAS congruent triangle proof (some missing statements and reasons).",
                "SAS congruent triangle proof (all reasons are missing).",
                "ASA congruent triangle proof.",
                "ASA congruent triangle proof (some missing statements and reasons).",
                "ASA congruent triangle proof (all reasons missing).",
                "AAS congruent triangle proof.",
                "AAS congruent triangle proof (some missing statements and reasons).",
                "AAS congruent triangle proof (all reasons missing).",
                "HL congruent triangle proof.",
                "HL congruent triangle proof (some missing statements and reasons).",
                "HL congruent triangle proof (all reasons missing).",
            ]
            "Similar Polygons": [
                "Similar polygons.",
                "Similar polygons word problem.",
                "Length, perimeter, and area ratio word problem.",
                "Scale factor and area ratio word problem.",
                "Find a side of a triangle using similar triangles.",
                "Similar triangles.",
                "Similar triangles II.",
                "Similar triangles III.",
                "Similar triangles IV.",
                "Geometric mean.",
            ]
            "Circles": [
                "Radius and tangent.",
                "Arcs and central angles.",
                "Arcs and central angles II.",
                "Inscribed angles.",
                "Inscribed angles II.",
                "Inscribed angles III.",
                "Central angle and arc word problem.",
                "External angles formed by tangents.",
                "External angles formed by secants.",
                "Angles formed by 2 chords.",
                "Segments formed by 2 chords.",
                "Segments formed by 2 secants.",
                "Segments formed by a secant and a tangent.",
                "Area of a sector of a circle word problem.",
            ]
            "Perimeter and Area": [
                "Perimeter.",
                "Given the perimeter of a square, find the length of each side.",
                "Given the perimeter of a rectangle, find the length or width.",
                "Perimeter of a rectangle.",
                "Perimeter of a triangle.",
                "Perimeter of a trapezoid.",
                "Perimeter of a parallelogram.",
                "Area of a square.",
                "Given the area of a square, find the length of each side.",
                "Given the area of a rectangle, find the length or width.",
                "Area of a rectangle.",
                "Area of a square or rectangle.",
                "Area of a square or rectangle word problem.",
                "Area of a parallelogram.",
                "Area of a triangle.",
                "Area of a triangle word problem.",
                "Area of a trapezoid.",
                "Area of a trapezoid word problem.",
                "Area word problem.",
                "Circumference (pi).",
                "Circumference (3.14).",
                "Length of an arc given the degree. ",
                "Given the circumference of a circle, find the radius.",
                "Area of a circle (pi).",
                "Area of a circle (3.14).",
                "Area of a circle (sector)",
                "Area of a sector of a circle word problem.",
                "Given the area of a circle, find the radius.",
                "Area of a regular triangle (given apothem and length).",
                "Area of a regular triangle (given length).",
                "Area of a regular pentagon (given apothem and length).",
                "Area of a regular pentagon (given length).",
                "Area of a regular hexagon (given apothem and length).",
                "Area of a regular hexagon (given length).",
                "Area of combined shapes.",
                "Difference in Area (Rectangles).",
                "Difference in Area (Rectangle and Triangle).",
                "Difference in Area (Rectangle and Circle).",
                "Difference in Area (Circles).",
                "Difference in Area (Circle and Triangle).",
            ]
            "Surface Area and Volume": [
                "Surface area of a cube.",
                "Surface area of a rectangular prism.",
                "Surface area of a triangular prism.",
                "Surface area of a regular pyramid.",
                "Surface area of a cylinder (pi).",
                "Surface area of a cylinder (3.14).",
                "Surface area of a cone (pi).",
                "Surface area of a cone (3.14).",
                "Surface area of a cone II (pi).",
                "Surface area of a cone II (3.14).",
                "Surface area of a sphere (pi).",
                "Surface area of a sphere (3.14).",
                "Volume of a cube.",
                "Volume of a rectangular prism.",
                "Volume of a triangular prism.",
                "Volume of a regular pyramid.",
                "Volume of a cylinder (pi).",
                "Volume of a cylinder (3.14).",
                "Volume of a cone (pi).",
                "Volume of a cone (3.14).",
                "Volume of a sphere (pi).",
                "Volume of a sphere (3.14).",
                "Volume word problem.",
            ]
            "Coordinate Geometry": [
                "Plot and classify a quadrilateral.",
                "Find the distance between 2 points.",
                "Find the midpoint between 2 points.",
                "Find the area of a triangle from 3 points.",
                "Find the area of irregular shapes.",
                "Reflections.",
                "Translations.",
                "Rotations.",
            ]
            "Right Triangles and Trigonometry Functions": [
                "Pythagorean Theorem I.",
                "Pythagorean Theorem II.",
                "Pythagorean word problem (find the hypotenuse).",
                "Pythagorean word problem (find a leg).",
                "Pythagorean word problem (find the hypotenuse or leg).",
                "45-45-90 Triangle.",
                "45-45-90 Triangle II.",
                "45-45-90 Triangle word problem.",
                "30-60-90 Triangle.",
                "30-60-90 Triangle II.",
                "30-60-90 Triangle word problem.",
                "Sine, cosine, and tangent.",
                "Solving right triangles using sine.",
                "Solving right triangles using cosine.",
                "Solving right triangles using sine or cosine.",
                "Solving right triangles using tangent.",
                "Solving for an angle of a right triangle using cos, sin, or tan.",
                "Tangent word problem.",
                "Sine word problem.",
                "Cosine word problem.",
        ]
        },
        'enabled': False
    },
    'trigonometry': {
        'short name': 'Trigonometry',
        'description': 'Trigonometry',
        'categories': [],
        'enabled': False
    },
    'algebra_2': {
        'short name': 'Algebra II',
        'description': 'Algebra II',
        'categories': [],
        'enabled': False
    },
    'precalc': {
        'short name': 'Pre-Calculus',
        'description': 'Pre-Calculus',
        'categories': [],
        'enabled': False
    },
    'calculus': {
        'short name': 'Calculus',
        'description': 'Calculus',
        'categories': [],
        'enabled': False
    },
    'linear_algebra': {
        'short name': 'Linear Algebra',
        'description': 'Linear Algebra',
        'categories': [],
        'enabled': False
    },
    'diffeq': {
        'short name': 'Differential Equations',
        'description': 'Differential Equations',
        'categories': [],
        'enabled': False
    },
    'satprep': {
        'short name': 'SAT Preparation',
        'description': 'SAT Preparation',
        'categories': [],
        'enabled': False
    },
    'actprep': {
        'short name': 'ACT Preparation',
        'description': 'ACT Preparation',
        'categories': [],
        'enabled': False
    },
}
