PROBLEM_SUBJECTS = {
    'basic_math': {
        'short name': 'Basic Math',
        'description': 'Basic Mathematics',
        'categories': {
        "Whole Numbers": [
            "Place values (Whole Numbers).",
            "Rounding.",
            "Estimating sums.",
            "Simple addition (1 digit).",
            "Simple addition (1 - 2 digits).",
            "Addition (3 digits).",
            "Associative property (addition).",
            "Commutative property (addition).",
            "Addition word problem.",
            "Estimating differences.",
            "Simple subtraction (1 digit).",
            "Simple subtraction without borrowing (1 or 2 digits).",
            "Simple subtraction (1 or 2 digits).",
            "Subtraction.",
            "Subtraction (from 10x).",
            "Subtraction word problem.",
            "Simple multiplication (1 or 2 digits).",
            "Simple multiplication II.",
            "Simple multiplication (by 10x).",
            "Estimating products.",
            "Multiplication (2 or 3 digits).",
            "Write number in expanded form.",
            "Simplifying expanded form.",
            "Multiplication word problem.",
            "Simple division (no remainder).",
            "Simple division with zeros (no remainder).",
            "Estimating quotients.",
            "Simple division (with remainder).",
            "Division word problem.",
            "Long division (no remainder).",
            "Long division (with remainder).",
            "Square roots.",
            "Order of operations.",
            "Order of operations (exponents).",
            "Order of operations II.",
            "Telling time I.",
            "Telling time II.",
            "Passing Time.",
            "Passing Time Word Problem.",
            "Identify the operation word problem.",
            "Convert a Roman Numeral to a Standard Number.",
            "Convert to a Roman Numeral.",
            "Convert between place values.",
        ]
        "Decimals": [
            "Place values.",
            "Comparing decimals.",
            "Sorting decimals.",
            "Rounding decimals.",
            "Adding simple decimals.",
            "Adding decimals.",
            "Adding 3 decimals.",
            "Adding decimal word problem.",
            "Subtracting simple decimals.",
            "Subtracting decimals.",
            "Subtracting decimal word problem.",
            "Multiplying simple decimals.",
            "Multiplying 3 simple decimals.",
            "Multiplying decimals.",
            "Multiplying decimals (10x).",
            "Multiplying decimal word problem.",
            "Dividing simple decimals.",
            "Dividing decimals by whole numbers.",
            "Dividing decimals (10x).",
            "Dividing decimals by decimals.",
            "Dividing decimals by decimals II.",
            "Dividing decimal word problem.",
            "Write a number in scientific notation.",
            "Convert from scientific notation to standard notation.",
        ]
        "Fractions I": [
            "Identifying fractions.",
            "Identifying proper, improper, and mixed numbers.",
            "Plot a fraction on a number line.",
            "Find the greatest common factor of two numbers (GCF).",
            "Writing numbers as products of primes using exponents.",
            "Reducing fractions.",
            "Higher equivalent fractions.",
            "Comparing fractions.",
            "Sorting fractions.",
            "Improper fractions to mixed numbers.",
            "Mixed numbers to improper fractions.",
            "Multiplying simple fractions.",
            "Multiplying fractions word problem.",
            "Multiplying fractions with canceling.",
            "Multiplying 3 fractions.",
            "Multiplying a whole number and a fraction.",
            "Multiplying mixed numbers and a fraction.",
            "Multiplying mixed numbers and a whole number.",
            "Multiplying mixed numbers.",
            "Dividing simple fractions.",
            "Dividing with mixed numbers.",
            "Find a fraction of a number.",
            "Find what fraction.",
            "Find a number given a fraction of it.",
        ]
        "Fractions II": [
            "Finding the lowest common multiple.",
            "Finding the lowest common multiple word problem.",
            "Adding fractions with common denominators.",
            "Adding 3 fractions with common denominators.",
            "Adding mixed numbers with common denominators.",
            "Adding 3 mixed numbers with common denominators.",
            "Adding fractions using the commutative and associative properties.",
            "Adding fractions with uncommon denominators.",
            "Adding fractions with uncommon denominators (1 digit).",
            "Adding 3 fractions with uncommon denominators.",
            "Adding mixed numbers with uncommon denominators.",
            "Adding 3 mixed numbers with uncommon denominators.",
            "Adding mixed numbers word problem.",
            "Subtracting fractions with common denominators.",
            "Subtracting mixed numbers with common denominators.",
            "Subtracting fractions with uncommon denominators.",
            "Subtracting mixed numbers with uncommon denominators.",
            "Subtracting fractions from a whole number.",
            "Subtracting fractions with borrowing.",
            "Subtracting mixed numbers word problem.",
            "Converting fractions to decimals (no mixed numbers).",
            "Converting decimals to fractions (no mixed numbers).",
            "Converting fractions to decimals.",
            "Converting decimals to fractions.",
            "Repeating decimals to fractions.",
            "Sorting decimals and fractions.",
        ]
        "Ratios, Proportions, and Percents": [
            "Simplifying ratios.",
            "Ratio word problem.",
            "Ratio word problem II.",
            "Solving proportions (simple values).",
            "Solving proportions.",
            "Simple proportion word problem.",
            "Proportion word problem (height and shadow).",
            "Proportion word problem (fractions).",
            "Converting decimals to percents.",
            "Converting percents to decimals.",
            "Converting fractions to percents.",
            "Converting percents to fractions.",
            "Convert inches to centimeters.",
            "Convert centimeters to inches.",
            "Convert miles to kilometers.",
            "Convert kilometers to miles.",
            "Convert simple metric lengths.",
            "Convert simple English lengths.",
            "Convert simple metric masses.",
            "Convert simple English weights.",
            "Convert simple metric volumes.",
            "Convert simple English volumes.",
            "Convert using the metric system.",
            "Convert using the English system.",
            "Convert using the metric and English system.",
            "Convert between simple units of time.",
            "Converting simple metric lengths word problem.",
            "Converting simple English lengths word problem.",
            "Converting simple metric masses word problem.",
            "Converting simple English weights word problem.",
            "Converting between derived quantities word problem.",
            "Find the percent of a number.",
            "Find what percent.",
            "Find a number given its percent.",
            "Simple Percent word problem (percent of).",
            "Simple Percent word problem (find the whole).",
            "Simple Percent word problem (find the percent).",
            "Simple Percent word problem (sale).",
            "Percent word problem (sale).",
            "Simple Percent word problem (find the tax).",
            "Simple Percent word problem (tax).",
            "Percent word problem (tax).",
            "Percent word problem (find the tax percentage).",
            "Percent word problem (sale and tax).",
            "Find a fraction of a number.",
            "Find what fraction.",
            "Find a number given a fraction of it.",
        ]
        "Statistics and Probablity": [
            "Bar graphs.",
            "Bar graphs (smaller).",
            "Make a bar graph given when data.",
            "Line graphs.",
            "Line graphs (smaller).",
            "Pie charts.",
            "Analyzing graphs.",
            "Mean (whole answers).",
            "Mean.",
            "Mean word problem.",
            "Median.",
            "Median word problem.",
            "Mode.",
            "Mode (no mode added).",
            "Mode word problem.",
            "Range.",
            "Range word problems.",
            "Standard deviation.",
            "Simple reverse mean word problem (whole numbers).",
            "Reverse mean word problem (whole numbers).",
            "Reverse mean word problem.",
            "Overall average word problem.",
            "Basic probability word problem (marbles).",
            "Basic probability word problem (students).",
            "Probability word problem (with replacement).",
            "Probability word problem (no replacement).",
            "Experimental probability word problem.",
        ]
        "Basic Algebra": [
            "Adding integers (1-digit).",
            "Adding 3 - 4 integers (1-digit).",
            "Adding integers.",
            "Adding 3 - 4 integers.",
            "Adding integers word problem.",
            "Subtracting integers (1-digit).",
            "Subtracting integers.",
            "Multiplying integers (1-digit).",
            "Multiplying 3 - 4 integers (1-digit).",
            "Multiplying integers.",
            "Dividing integers (1-2 digits).",
            "Dividing integers.",
            "Integer word problem.",
            "Basic exponents (powers).",
            "Evaluate a basic root.",
            "Evaluating expressions (Basic one operation).",
            "Evaluating expressions (Basic two operations).",
            "Evaluating expressions I.",
            "Evaluating expressions II.",
            "Applying area formulas.",
            "Functions - Table.",
            "Functions.",
            "Solving single-step equations by subtraction (1-digit no negatives).",
            "Solving single-step equations by subtraction (1-digit).",
            "Solving single-step equations by subtraction.",
            "Solving single-step equations by addition (1-digit no negatives).",
            "Solving single-step equations by addition (1-digit).",
            "Solving single-step equations by addition.",
            "Solving single-step equations by addition or subtraction (1-digit).",
            "Solving single-step equations by addition or subtraction.",
            "Solving single-step equations by division (simple values no negatives).",
            "Solving single-step equations by division.",
            "Solving single-step equations by multiplication (1-digit no negatives).",
            "Solving single-step equations by multiplication.",
            "Solving two-step equations (simple values).",
            "Solving two-step equations.",
            "Plot a point on a coordinate plane.",
            "Find the slope given 2 points.",
            "Given a graph, calculate the slope.",
            "Graph by using an x-y table (y is isolated).",
            "Given a point and an equation in slope-intercept form, determine if the point exists on the line.",
            "Graph a line given an equation in slope-intercept form.",
        ]
        "Basic Geometry": [
            "Identifying shapes.",
            "Perimeter.",
            "Circumference (pi).",
            "Circumference (3.14).",
            "Area of a circle (pi).",
            "Area of a circle (3.14).",
            "Area of a square (blocks).",
            "Area of a rectangle (blocks).",
            "Volume of a cube (blocks).",
            "Volume of a rectangular solid (blocks).",
            "Area of a square or rectangle.",
            "Area of a parallelogram.",
            "Area of a triangle.",
            "Area of a trapezoid.",
            "Area word problem.",
            "Volume of a cube.",
            "Volume of a rectangular prism.",
            "Volume of a cylinder (pi).",
            "Volume of a cylinder (3.14).",
            "Volume of a sphere (pi).",
            "Volume of a sphere (3.14).",
            "Similar polygons.",
            "Pythagorean theorem.",
            "Pythagorean theorem word problem.",
        ]
        }
        'enabled': False
    },
    'algebra_1': {
        'short name': 'Algebra I',
        'description': 'Algebra I',
        'categories': [],
        'enabled': False
    },
    'geometry': {
        'short name': 'Geometry',
        'description': 'Geometry',
        'categories': [],
        'enabled': False
    },
    'trigonometry': {
        'short name': 'Trigonometry',
        'description': 'Trigonometry',
        'categories': [],
        'enabled': False
    },
    'algebra_2': {
        'short name': 'Algebra II',
        'description': 'Algebra II',
        'categories': [],
        'enabled': False
    },
    'precalc': {
        'short name': 'Pre-Calculus',
        'description': 'Pre-Calculus',
        'categories': [],
        'enabled': False
    },
    'calculus': {
        'short name': 'Calculus',
        'description': 'Calculus',
        'categories': [],
        'enabled': False
    },
    'linear_algebra': {
        'short name': 'Linear Algebra',
        'description': 'Linear Algebra',
        'categories': [],
        'enabled': False
    },
    'diffeq': {
        'short name': 'Differential Equations',
        'description': 'Differential Equations',
        'categories': [],
        'enabled': False
    },
    'satprep': {
        'short name': 'SAT Preparation',
        'description': 'SAT Preparation',
        'categories': [],
        'enabled': False
    },
    'actprep': {
        'short name': 'ACT Preparation',
        'description': 'ACT Preparation',
        'categories': [],
        'enabled': False
    },
}
